#!/bin/bash

#Проверка на наличие репозитория и его добавление
echo "Проверка наличия репозитория backports и его добавление"
if cat /etc/apt/sources.list | grep -e "backports"
then echo "Репозиторий есть"
else echo "Репозиторий не найден, добавляем" && echo "deb http://deb.debian.org/debian bullseye-backports main contrib non-free" | sudo tee -a /etc/apt/sources.list 
fi
echo "\n"

#Обновление пакетов
echo "Обновление пакетов"
sudo apt-get update -y
echo "\n"

#Устанавновка и запуск Apache2
echo "Установка и запуск Apache2"
sudo apt install apache2 -y
sudo systemctl start apache2
echo "\n"

#Установка Python
echo "Установка Python"
sudo apt install python3 -y
echo "\n"

#Установка и поднятие сервера SSH
echo "Установка и запуск SSH"
sudo apt install ssh -y
sudo systemctl start ssh
echo "\n"

#Информация о жестком диске
echo "Информация о жёстком диске"
sudo apt install smartmontools -y
sudo smartctl -i /dev/sda
echo "\n"

#Мониторинг дискового пространства
echo "ТОП-10 директорий по занимаемому месту"
read -p "Имя директории: " my_direct
sudo du -S $my_direct | sort -rn | head | cat -n | awk '{printf $1 ":" "\t" $2 "\t" $3 "\n"}'
echo "\n"

#Поиск файла по имени в заданной директории
echo "Поиск файла по заданному имени в заданной директории"
read -p "Имя файла: " name
read -p "Имя директории: " directories
for dir in $directories
do
if [ -f "$dir/$name" ]
then echo "Файл '$name' находится в '$dir'\n"
else echo "Файл '$name' не найден в заданных директориях"
fi
done
echo "\n"

#Очистка кэша
echo "Очистка кэша памяти"
free -m
sync; echo 3 > sudo /proc/sys/vm/drop_caches && free -m
echo "\n"

#Проверка скорости
echo "Проверка скорости работы интернета"
sudo sudo apt install python3-pip -y
sudo sudo pip install speedtest-cli
echo "Информация о ping, скорости загрузки и отдачи"
sudo speedtest-cli --simple
